name: cam_sport_deploy

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  
env:
  POSTGRES_DB: c23_bad_gp2_tw_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  
jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: testing
        run: |
          cd server
          yarn install 
          yarn knex migrate:latest --env test
          yarn test
  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd BAD-Project
          git checkout production
          git pull origin production
          cd server
          yarn install
          yarn knex migrate:latest --env production
          yarn build
          forever restart 0
        host: cam-sport.me
        user: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
